## Importing Libraries

In [1]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
from sodapy import Socrata
import seaborn as sns
import os 
from dotenv import load_dotenv

## Reading In Data

In [2]:
load_dotenv() 
api = os.getenv('MY_API')
MyAppToken = os.getenv('MyAppToken')

In [3]:
client = Socrata("data.cityofnewyork.us",
                  MyAppToken,
                  )

In [ ]:
results = client.get("erm2-nwe9", limit=1000000, where=" agency = 'NYPD' and created_date > '2022-01-01T00:00:00' and created_date < '2026-01-01T00:00:00' ")

## Data Inspection

In [ ]:
results_df = pd.DataFrame.from_records(results)
results_df

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,...,park_borough,latitude,longitude,location,vehicle_type,bridge_highway_name,bridge_highway_direction,bridge_highway_segment,descriptor_2,road_ramp
0,59488711,2023-11-18T11:53:22.000,2023-11-18T12:09:47.000,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,10027,357 WEST 125 STREET,...,MANHATTAN,40.81091562544085,-73.95292239111768,"{'type': 'Point', 'coordinates': [-73.95292239...",NaN,NaN,NaN,NaN,NaN,NaN
1,59483528,2023-11-18T02:45:59.000,2023-11-18T03:14:18.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10014,51 BANK STREET,...,MANHATTAN,40.73680352159004,-74.00401258977008,"{'type': 'Point', 'coordinates': [-74.00401258...",NaN,NaN,NaN,NaN,NaN,NaN
2,59488664,2023-11-18T12:55:50.000,2023-11-18T13:45:18.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11249,84 NORTH 9 STREET,...,BROOKLYN,40.72045950290502,-73.95899648144866,"{'type': 'Point', 'coordinates': [-73.95899648...",NaN,NaN,NaN,NaN,NaN,NaN
3,59485258,2023-11-19T01:15:22.000,2023-11-19T10:01:19.000,NYPD,New York City Police Department,Illegal Parking,Blocked Crosswalk,Street/Sidewalk,11420,124-01 133 AVENUE,...,QUEENS,40.67134812197744,-73.81466460256136,"{'type': 'Point', 'coordinates': [-73.81466460...",NaN,NaN,NaN,NaN,NaN,NaN
4,59489530,2023-11-19T19:19:42.000,2023-11-19T19:51:34.000,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10032,ST NICHOLAS AVENUE,...,MANHATTAN,40.83309826087525,-73.9406527495994,"{'type': 'Point', 'coordinates': [-73.94065274...",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,55280267,2022-09-01T21:26:33.000,2022-09-01T21:53:43.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11420,123-47 135 STREET,...,QUEENS,40.67420352793922,-73.80358551110304,"{'type': 'Point', 'coordinates': [-73.80358551...",NaN,NaN,NaN,NaN,NaN,NaN
999996,55281480,2022-09-01T14:17:46.000,2022-09-01T15:08:09.000,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,10467,2407 BOSTON ROAD,...,BRONX,40.86110685298939,-73.86689232523966,"{'type': 'Point', 'coordinates': [-73.86689232...",NaN,NaN,NaN,NaN,NaN,NaN
999997,55297002,2022-09-03T12:47:10.000,2022-09-03T14:19:45.000,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11228,8118 14 AVENUE,...,BROOKLYN,40.615423849305984,-74.00892906699623,"{'type': 'Point', 'coordinates': [-74.00892906...",NaN,NaN,NaN,NaN,NaN,NaN
999998,55295155,2022-09-03T23:23:52.000,2022-09-04T00:07:54.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11418,104-38 92 AVENUE,...,QUEENS,40.69195084920274,-73.84059955256502,"{'type': 'Point', 'coordinates': [-73.84059955...",NaN,NaN,NaN,NaN,NaN,NaN
999999,55291364,2022-09-02T02:31:36.000,2022-09-02T03:16:18.000,NYPD,New York City Police Department,Encampment,N/A,Subway,NaN,NaN,...,BROOKLYN,40.625656729910986,-73.99662451855306,"{'type': 'Point', 'coordinates': [-73.99662451...",NaN,N,NaN,Mezzanine,NaN,NaN

In [ ]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 40 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   unique_key                      1000000 non-null  object
 1   created_date                    1000000 non-null  object
 2   closed_date                     999885 non-null   object
 3   agency                          1000000 non-null  object
 4   agency_name                     1000000 non-null  object
 5   complaint_type                  1000000 non-null  object
 6   descriptor                      1000000 non-null  object
 7   location_type                   999996 non-null   object
 8   incident_zip                    989331 non-null   object
 9   incident_address                989390 non-null   object
 10  street_name                     989367 non-null   object
 11  cross_street_1                  988182 non-null   object
 12  cross_street_2                  988529 non-null   object
 13  intersection_street_1           988182 non-null   object
 14  intersection_street_2           988529 non-null   object
 15  address_type                    989368 non-null   object
 16  city                            932732 non-null   object
 17  landmark                        932699 non-null   object
 18  status                          1000000 non-null  object
 19  resolution_description          999782 non-null   object
 20  resolution_action_updated_date  999935 non-null   object
 21  community_board                 1000000 non-null  object
 22  council_district                983384 non-null   object
 23  police_precinct                 1000000 non-null  object
 24  bbl                             896996 non-null   object
 25  borough                         1000000 non-null  object
 26  x_coordinate_state_plane        993168 non-null   object
 27  y_coordinate_state_plane        993282 non-null   object
 28  open_data_channel_type          1000000 non-null  object
 29  park_facility_name              1000000 non-null  object
 30  park_borough                    1000000 non-null  object
 31  latitude                        993160 non-null   object
 32  longitude                       993160 non-null   object
 33  location                        993160 non-null   object
 34  vehicle_type                    13256 non-null    object
 35  bridge_highway_name             10377 non-null    object
 36  bridge_highway_direction        3700 non-null     object
 37  bridge_highway_segment          10377 non-null    object
 38  descriptor_2                    10047 non-null    object
 39  road_ramp                       1740 non-null     object
dtypes: object(40)
memory usage: 305.2+ MB

In [ ]:
results_df['created_date'] = pd.to_datetime(results_df['created_date'])
results_df['closed_date'] = pd.to_datetime(results_df['closed_date'])

In [ ]:
# inspecting date range
min_date = results_df['created_date'].min()
max_date = results_df['created_date'].max()

print(f'This dataset is from {min_date} to {max_date}')

This dataset is from 2022-01-01 00:00:10 to 2025-12-31 23:59:28

## Inspecting Items In Each Column

In [ ]:
# preview first five rows, first 15 columns
results_df.iloc[-5:, :15]

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2
999995,55280267,2022-09-01 21:26:33,2022-09-01 21:53:43,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11420,123-47 135 STREET,135 STREET,ROCKAWAY BOULEVARD,SUTTER AVENUE,ROCKAWAY BOULEVARD,SUTTER AVENUE
999996,55281480,2022-09-01 14:17:46,2022-09-01 15:08:09,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,10467,2407 BOSTON ROAD,BOSTON ROAD,WHITE PLAINS ROAD,WARING AVENUE,WHITE PLAINS ROAD,WARING AVENUE
999997,55297002,2022-09-03 12:47:10,2022-09-03 14:19:45,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11228,8118 14 AVENUE,14 AVENUE,81 STREET,82 STREET,81 STREET,82 STREET
999998,55295155,2022-09-03 23:23:52,2022-09-04 00:07:54,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11418,104-38 92 AVENUE,92 AVENUE,105 STREET,107 STREET,105 STREET,107 STREET
999999,55291364,2022-09-02 02:31:36,2022-09-02 03:16:18,NYPD,New York City Police Department,Encampment,N/A,Subway,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# preview first five rows, 15th to the 30th column
results_df.iloc[-10:, 15:30]

,address_type,city,landmark,status,resolution_description,resolution_action_updated_date,community_board,council_district,police_precinct,bbl,borough,x_coordinate_state_plane,y_coordinate_state_plane,open_data_channel_type,park_facility_name
999990,ADDRESS,NEW YORK,WEST 93 STREET,Closed,The Police Department responded to the complai...,2022-09-03T23:07:16.000,07 MANHATTAN,06,Precinct 24,1012410025,MANHATTAN,992055,227882,ONLINE,Unspecified
999991,ADDRESS,BROOKLYN,SCHAEFER STREET,Closed,The Police Department responded and upon arriv...,2022-09-03T20:00:41.000,04 BROOKLYN,37,Precinct 83,3034230058,BROOKLYN,1009762,190496,ONLINE,Unspecified
999992,ADDRESS,BRONX,BRYANT AVENUE,Closed,The Police Department issued a summons in resp...,2022-09-03T11:57:11.000,03 BRONX,17,Precinct 42,2029930039,BRONX,1014973,241332,PHONE,Unspecified
999993,ADDRESS,SOUTH RICHMOND HILL,108 STREET,Closed,The Police Department responded to the complai...,2022-09-03T17:21:35.000,10 QUEENS,32,Precinct 106,4095300012,QUEENS,1030441,188154,ONLINE,Unspecified
999994,ADDRESS,STATEN ISLAND,SCARBORO AVENUE,Closed,The Police Department responded to the complai...,2022-09-03T13:15:37.000,01 STATEN ISLAND,49,Precinct 120,5028320119,STATEN ISLAND,966522,162636,ONLINE,Unspecified
999995,ADDRESS,SOUTH OZONE PARK,135 STREET,Closed,The Police Department responded to the complai...,2022-09-01T21:53:47.000,10 QUEENS,28,Precinct 106,4117590020,QUEENS,1038733,184968,ONLINE,Unspecified
999996,ADDRESS,BRONX,BOSTON ROAD,Closed,The Police Department responded to the complai...,2022-09-01T15:08:13.000,11 BRONX,15,Precinct 49,2043460058,BRONX,1021069,253030,ONLINE,Unspecified
999997,ADDRESS,BROOKLYN,14 AVENUE,Closed,The Police Department issued a summons in resp...,2022-09-03T14:19:50.000,10 BROOKLYN,43,Precinct 68,3062920043,BROOKLYN,981771,163492,MOBILE,Unspecified
999998,ADDRESS,RICHMOND HILL,92 AVENUE,Closed,The Police Department responded to the complai...,2022-09-04T00:08:03.000,09 QUEENS,32,Precinct 102,4093120019,QUEENS,1028454,191413,ONLINE,Unspecified
999999,NaN,NaN,NaN,Closed,The Police Department visited the location and...,2022-09-02T03:16:20.000,Unspecified BROOKLYN,NaN,Unspecified,NaN,BROOKLYN,985187,167220,MOBILE,Unspecified

In [ ]:
# preview first five rows, 30th to the last column
results_df.iloc[-5:, 30:]

,park_borough,latitude,longitude,location,vehicle_type,bridge_highway_name,bridge_highway_direction,bridge_highway_segment,descriptor_2,road_ramp
999995,QUEENS,40.67420352793922,-73.80358551110304,"{'type': 'Point', 'coordinates': [-73.80358551...",NaN,NaN,NaN,NaN,NaN,NaN
999996,BRONX,40.86110685298939,-73.86689232523966,"{'type': 'Point', 'coordinates': [-73.86689232...",NaN,NaN,NaN,NaN,NaN,NaN
999997,BROOKLYN,40.615423849305984,-74.00892906699623,"{'type': 'Point', 'coordinates': [-74.00892906...",NaN,NaN,NaN,NaN,NaN,NaN
999998,QUEENS,40.69195084920274,-73.84059955256502,"{'type': 'Point', 'coordinates': [-73.84059955...",NaN,NaN,NaN,NaN,NaN,NaN
999999,BROOKLYN,40.625656729910986,-73.99662451855306,"{'type': 'Point', 'coordinates': [-73.99662451...",NaN,N,NaN,Mezzanine,NaN,NaN

In [ ]:
print('Top 15 Resolution Descriptions In Descending Order:\n')

for i in range(0, 16):
    res = results_df['resolution_description'].value_counts().index[i]
    count = results_df['resolution_description'].value_counts()[i]
    
    print(f'{i}. {res}')
    print(f'-- Count: {count:,}\n')

Top 15 Resolution Descriptions In Descending Order:

0. The Police Department responded to the complaint and with the information available observed no evidence of the violation at that time.
-- Count: 264,452

1. The Police Department responded to the complaint and took action to fix the condition.
-- Count: 261,063

2. The Police Department responded to the complaint and determined that police action was not necessary.
-- Count: 142,748

3. The Police Department issued a summons in response to the complaint.
-- Count: 94,366

4. The Police Department responded and upon arrival those responsible for the condition were gone.
-- Count: 90,405

5. The Police Department reviewed your complaint and provided additional information below.
-- Count: 35,708

6. The Police Department responded to the complaint but officers were unable to gain entry into the premises.
-- Count: 17,627

7. The Police Department visited the location and no Encampment was found.
-- Count: 16,757

8. This complaint does not fall under the Police Department's jurisdiction.
-- Count: 12,356

9. The New York City Police Department responded to the complaint and with the information available observed no evidence of a criminal violation at that time. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. If necessary, your complaint may be referred to your local precinct's special operations units (Quality of Life, etc.). We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
-- Count: 11,985

10. The New York City Police Department responded to the complaint and their investigation determined that no criminal violation existed. The condition was corrected without the need to issue a summons or effect an arrest. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. If necessary, your complaint may be referred to your local precinct's special operations units (Quality of Life, etc.). Thank you for your attention to this matter. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
-- Count: 11,015

11. The New York City Police Department responded to the complaint and observed no criminal violation upon their arrival. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
-- Count: 8,502

12. The New York City Police Department responded to the complaint and their investigation determined that a violation of law occurred. Police issued a summons in response to the complaint. Thank you for attention to this matter. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
-- Count: 7,983

13. The New York City Police Department responded to the complaint and their investigation determined that police action was not necessary. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
-- Count: 7,696

14. The Police Department visited the location and has referred the complaint to the Department of Homeless Services (DHS) for further action. DHS will inspect the condition and update your Service Request with more information.
-- Count: 6,675

15. Your request can not be processed at this time because of insufficient contact information. Please create a new Service Request on NYC.gov and provide more detailed contact information.
-- Count: 4,791

## Identifying Null Values

In [ ]:
# calculating percentage of nulls values for each column
missing_data = (
    results_df
    .isnull()
    .sum()
    .div(results_df.shape[0])
    .mul(100)
)

missing_data.sort_values(ascending=False)

road_ramp                         99.8260
bridge_highway_direction          99.6300
descriptor_2                      98.9953
bridge_highway_name               98.9623
bridge_highway_segment            98.9623
vehicle_type                      98.6744
bbl                               10.3004
landmark                           6.7301
city                               6.7268
council_district                   1.6616
intersection_street_1              1.1818
cross_street_1                     1.1818
intersection_street_2              1.1471
cross_street_2                     1.1471
incident_zip                       1.0669
street_name                        1.0633
address_type                       1.0632
incident_address                   1.0610
location                           0.6840
longitude                          0.6840
latitude                           0.6840
x_coordinate_state_plane           0.6832
y_coordinate_state_plane           0.6718
resolution_description             0.0218
closed_date                        0.0115
resolution_action_updated_date     0.0065
location_type                      0.0004
borough                            0.0000
police_precinct                    0.0000
open_data_channel_type             0.0000
park_facility_name                 0.0000
park_borough                       0.0000
community_board                    0.0000
created_date                       0.0000
status                             0.0000
descriptor                         0.0000
complaint_type                     0.0000
agency_name                        0.0000
agency                             0.0000
unique_key                         0.0000
dtype: float64

In [ ]:
(results_df
 .groupby(['police_precinct'])['unique_key']
 .count()
 .sort_values(ascending=True)
 .tail(40)
)

police_precinct
Precinct 79     11559
Precinct 32     11631
Precinct 103    11650
Precinct 84     11845
Precinct 40     11912
Precinct 90     11992
Precinct 77     12001
Unspecified     12017
Precinct 113    12030
Precinct 42     12053
Precinct 30     12077
Precinct 45     12302
Precinct 94     12353
Precinct 105    12543
Precinct 33     12904
Precinct 66     13022
Precinct 68     13758
Precinct 49     14138
Precinct 61     14462
Precinct 67     14533
Precinct 108    15073
Precinct 70     16036
Precinct 83     16684
Precinct 110    17717
Precinct 115    18469
Precinct 107    18926
Precinct 106    19160
Precinct 62     19652
Precinct 43     20120
Precinct 50     20206
Precinct 109    21363
Precinct 34     21652
Precinct 102    21960
Precinct 52     22522
Precinct 46     22863
Precinct 44     24157
Precinct 75     25784
Precinct 114    28594
Precinct 104    31086
Precinct 47     76365
Name: unique_key, dtype: int64

It looks like there is a default value assigned to null values

In [ ]:
results_df.loc[results_df['status'] != 'Closed', :]

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,...,park_borough,latitude,longitude,location,vehicle_type,bridge_highway_name,bridge_highway_direction,bridge_highway_segment,descriptor_2,road_ramp
74216,59688359,2023-12-09 09:22:51,2023-12-09 09:31:56,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11230,1997 OCEAN AVENUE,...,BROOKLYN,40.61293093865043,-73.95396245369524,"{'type': 'Point', 'coordinates': [-73.95396245...",NaN,NaN,NaN,NaN,NaN,NaN
92724,67246761,2025-12-20 22:37:55,2025-12-20 22:38:01,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,11693,88-12 ROCKAWAY BEACH BOULEVARD,...,QUEENS,40.58718818959647,-73.8135696335667,"{'type': 'Point', 'coordinates': [-73.81356963...",NaN,NaN,NaN,NaN,NaN,NaN
103721,67353039,2025-12-31 14:44:22,2025-12-31 14:44:30,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10466,655 EAST 230 STREET,...,BRONX,40.89187241649303,-73.86016845296459,"{'type': 'Point', 'coordinates': [-73.86016845...",NaN,NaN,NaN,NaN,NaN,NaN
134743,53210829,2022-01-29 18:02:37,NaT,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11236,AVENUE M,...,BROOKLYN,40.63907864457371,-73.8903270044555,"{'type': 'Point', 'coordinates': [-73.89032700...",NaN,NaN,NaN,NaN,NaN,NaN
135526,53206289,2022-01-29 17:06:35,NaT,NYPD,New York City Police Department,Panhandling,N/A,Subway,NaN,NaN,...,MANHATTAN,40.785863661153016,-73.95092872008252,"{'type': 'Point', 'coordinates': [-73.95092872...",NaN,6,NaN,Entrance,NaN,E 96 St & Lexington Av
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804735,54834022,2022-07-18 04:44:58,2022-07-18 04:45:01,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10466,672 EAST 231 STREET,...,BRONX,40.89238451539139,-73.8592161325675,"{'type': 'Point', 'coordinates': [-73.85921613...",NaN,NaN,NaN,NaN,NaN,NaN
819762,54887511,2022-07-24 21:08:04,2022-07-24 21:08:08,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10466,672 EAST 231 STREET,...,BRONX,40.89238451539139,-73.8592161325675,"{'type': 'Point', 'coordinates': [-73.85921613...",NaN,NaN,NaN,NaN,NaN,NaN
856945,54959553,2022-07-30 22:06:24,2022-07-30 22:06:28,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10466,672 EAST 231 STREET,...,BRONX,40.89238451539139,-73.8592161325675,"{'type': 'Point', 'coordinates': [-73.85921613...",NaN,NaN,NaN,NaN,NaN,NaN
859334,54962401,2022-07-30 21:28:23,2022-07-30 21:28:27,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10466,672 EAST 231 STREET,...,BRONX,40.89238451539139,-73.8592161325675,"{'type': 'Point', 'coordinates': [-73.85921613...",NaN,NaN,NaN,NaN,NaN,NaN
976690,55242987,2022-08-29 22:27:23,2022-08-29 22:33:06,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10466,672 EAST 231 STREET,...,BRONX,40.89238451539139,-73.8592161325675,"{'type': 'Point', 'coordinates': [-73.85921613...",NaN,NaN,NaN,NaN,NaN,NaN

The analysis is on closed status so I removed the 'In Progress' status

In [ ]:
results_df = results_df[results_df["status"] != "In Progress"]
results_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999885 entries, 0 to 999999
Data columns (total 40 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   unique_key                      999885 non-null  object
 1   created_date                    999885 non-null  datetime64[ns]
 2   closed_date                     999885 non-null  datetime64[ns]
 3   agency                          999885 non-null  object
 4   agency_name                     999885 non-null  object
 5   complaint_type                  999885 non-null  object
 6   descriptor                      999885 non-null  object
 7   location_type                   999881 non-null  object
 8   incident_zip                    989220 non-null  object
 9   incident_address                989279 non-null  object
 10  street_name                     989256 non-null  object
 11  cross_street_1                  988071 non-null  object
 12  cross_street_2                  988418 non-null  object
 13  intersection_street_1           988071 non-null  object
 14  intersection_street_2           988418 non-null  object
 15  address_type                    989257 non-null  object
 16  city                            932622 non-null  object
 17  landmark                        932589 non-null  object
 18  status                          999885 non-null  object
 19  resolution_description          999782 non-null  object
 20  resolution_action_updated_date  999820 non-null  object
 21  community_board                 999885 non-null  object
 22  council_district                983273 non-null  object
 23  police_precinct                 999885 non-null  object
 24  bbl                             896888 non-null  object
 25  borough                         999885 non-null  object
 26  x_coordinate_state_plane        993053 non-null  object
 27  y_coordinate_state_plane        993167 non-null  object
 28  open_data_channel_type          999885 non-null  object
 29  park_facility_name              999885 non-null  object
 30  park_borough                    999885 non-null  object
 31  latitude                        993045 non-null  object
 32  longitude                       993045 non-null  object
 33  location                        993045 non-null  object
 34  vehicle_type                    13256 non-null   object
 35  bridge_highway_name             10373 non-null   object
 36  bridge_highway_direction        3700 non-null    object
 37  bridge_highway_segment          10373 non-null   object
 38  descriptor_2                    10046 non-null   object
 39  road_ramp                       1739 non-null    object
dtypes: datetime64[ns](2), object(38)
memory usage: 312.8+ MB

## Selection of Impactful Variables

In [ ]:
NYPD = results_df[['created_date', 'closed_date','complaint_type','resolution_description','borough','latitude','longitude', 'x_coordinate_state_plane','y_coordinate_state_plane']]
NYPD

,unique_key,created_date,closed_date,complaint_type,descriptor,resolution_description,location_type,borough,latitude,longitude,x_coordinate_state_plane,y_coordinate_state_plane
0,59488711,2023-11-18 11:53:22,2023-11-18 12:09:47,Noise - Street/Sidewalk,Loud Talking,The Police Department responded to the complai...,Street/Sidewalk,MANHATTAN,40.81091562544085,-73.95292239111768,997282,234719
1,59483528,2023-11-18 02:45:59,2023-11-18 03:14:18,Noise - Residential,Loud Music/Party,The Police Department responded to the complai...,Residential Building/House,MANHATTAN,40.73680352159004,-74.00401258977008,983138,207714
2,59488664,2023-11-18 12:55:50,2023-11-18 13:45:18,Noise - Residential,Loud Music/Party,The Police Department responded to the complai...,Residential Building/House,BROOKLYN,40.72045950290502,-73.95899648144866,995616,201762
3,59485258,2023-11-19 01:15:22,2023-11-19 10:01:19,Illegal Parking,Blocked Crosswalk,The Police Department responded to the complai...,Street/Sidewalk,QUEENS,40.67134812197744,-73.81466460256136,1035662,183921
4,59489530,2023-11-19 19:19:42,2023-11-19 19:51:34,Noise - Commercial,Loud Music/Party,The Police Department responded to the complai...,Club/Bar/Restaurant,MANHATTAN,40.83309826087525,-73.9406527495994,1000673,242803
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,55280267,2022-09-01 21:26:33,2022-09-01 21:53:43,Noise - Residential,Loud Music/Party,The Police Department responded to the complai...,Residential Building/House,QUEENS,40.67420352793922,-73.80358551110304,1038733,184968
999996,55281480,2022-09-01 14:17:46,2022-09-01 15:08:09,Noise - Commercial,Loud Music/Party,The Police Department responded to the complai...,Store/Commercial,BRONX,40.86110685298939,-73.86689232523966,1021069,253030
999997,55297002,2022-09-03 12:47:10,2022-09-03 14:19:45,Blocked Driveway,No Access,The Police Department issued a summons in resp...,Street/Sidewalk,BROOKLYN,40.615423849305984,-74.00892906699623,981771,163492
999998,55295155,2022-09-03 23:23:52,2022-09-04 00:07:54,Noise - Residential,Loud Music/Party,The Police Department responded to the complai...,Residential Building/House,QUEENS,40.69195084920274,-73.84059955256502,1028454,191413
999999,55291364,2022-09-02 02:31:36,2022-09-02 03:16:18,Encampment,N/A,The Police Department visited the location and...,Subway,BROOKLYN,40.625656729910986,-73.99662451855306,985187,167220

In [ ]:
NYPD[ NYPD['location_type'] == 'Subway']

,unique_key,created_date,closed_date,complaint_type,descriptor,resolution_description,location_type,borough,latitude,longitude,x_coordinate_state_plane,y_coordinate_state_plane
160,59485171,2023-11-18 06:39:57,2023-11-18 07:08:46,Panhandling,N/A,The Police Department responded to the complai...,Subway,MANHATTAN,40.764810655208066,-73.97334765434452,991633,217919
213,59484108,2023-11-18 12:20:05,2023-11-18 12:59:27,Panhandling,N/A,The Police Department responded to the complai...,Subway,MANHATTAN,40.764810655208066,-73.97334765434452,991633,217919
299,59491016,2023-11-19 03:47:30,2023-11-19 03:59:29,Encampment,N/A,The Police Department visited the location and...,Subway,BROOKLYN,40.67731508862104,-73.9831131247339,988934,186041
653,59488120,2023-11-18 23:56:34,2023-11-19 00:50:54,Panhandling,N/A,The Police Department responded to the complai...,Subway,MANHATTAN,40.74287750319516,-73.99282215047695,986239,209927
755,59480955,2023-11-17 17:37:56,2023-11-17 18:08:42,Panhandling,N/A,The Police Department responded and upon arriv...,Subway,BRONX,40.83728574765848,-73.88773435188425,1015315,244343
...,...,...,...,...,...,...,...,...,...,...,...,...
999835,55288060,2022-09-02 13:19:24,2022-09-02 14:03:51,Panhandling,N/A,The Police Department responded and upon arriv...,Subway,MANHATTAN,40.76265731173501,-73.96762691181672,993218,217135
999848,55292468,2022-09-02 04:45:04,2022-09-02 05:18:30,Encampment,N/A,The Police Department visited the location and...,Subway,BROOKLYN,40.66889502741585,-73.93294405917439,1002852,182980
999877,55291366,2022-09-02 07:20:46,2022-09-02 08:40:30,Encampment,N/A,The Police Department visited the location and...,Subway,QUEENS,40.73612013887225,-73.87681616028804,1018388,207489
999931,55297792,2022-09-03 04:31:45,2022-09-03 04:51:38,Encampment,N/A,The Police Department visited the location and...,Subway,MANHATTAN,40.73986321079606,-73.98660123196585,987963,208829
999999,55291364,2022-09-02 02:31:36,2022-09-02 03:16:18,Encampment,N/A,The Police Department visited the location and...,Subway,BROOKLYN,40.625656729910986,-73.99662451855306,985187,167220

## Measuring Time to Complaint Resolution

In [ ]:
NYPD['duration'] = (NYPD['closed_date'] - NYPD['created_date'])
NYPD

/var/folders/wy/psj108nd3478hbn8njppcqqc0000gn/T/ipykernel_1444/1254131931.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NYPD['duration'] = (NYPD['closed_date'] - NYPD['created_date'])

,unique_key,created_date,closed_date,complaint_type,descriptor,resolution_description,location_type,incident_address,city,police_precinct,council_district,borough,latitude,longitude,x_coordinate_state_plane,y_coordinate_state_plane,duration
0,67231266,2025-12-18 09:07:05,2025-12-18 09:11:16,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,222 BAY 23 STREET,BROOKLYN,Precinct 62,47,BROOKLYN,40.60056381599916,-74.0036803047438,983228,158078,0 days 00:04:11
1,67231267,2025-12-18 07:26:24,2025-12-18 21:18:01,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,33 FOUNTAIN AVENUE,BROOKLYN,Precinct 75,37,BROOKLYN,40.6793441596136,-73.87635860175276,1018544,186804,0 days 13:51:37
2,67231268,2025-12-18 07:16:56,2025-12-18 10:56:33,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,128-03 25 AVENUE,COLLEGE POINT,Precinct 109,19,QUEENS,40.7765388831131,-73.84065703500205,1028382,222231,0 days 03:39:37
3,67231269,2025-12-18 11:51:57,2025-12-18 13:16:52,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,6112 DELAFIELD AVENUE,BRONX,Precinct 50,11,BRONX,40.91038734301122,-73.90215832177458,1011294,270972,0 days 01:24:55
4,67231270,2025-12-19 00:29:40,2025-12-19 01:09:00,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,1581 EAST 5 STREET,BROOKLYN,Precinct 66,44,BROOKLYN,40.61230758249285,-73.96960873273228,992688,162358,0 days 00:39:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,55457217,2022-09-18 01:13:43,2022-09-18 02:03:43,Noise - Street/Sidewalk,Loud Music/Party,The Police Department responded to the complai...,Street/Sidewalk,575 OLMSTEAD AVENUE,BRONX,Precinct 43,18,BRONX,40.818193053180714,-73.8510020850777,1025491,237402,0 days 00:50:00
999996,55466531,2022-09-19 19:37:52,2022-09-19 21:56:56,Illegal Parking,Double Parked Blocking Vehicle,The Police Department responded to the complai...,Street/Sidewalk,1150 EAST 42 STREET,BROOKLYN,Precinct 63,45,BROOKLYN,40.626818928731794,-73.93546845515829,1002163,167650,0 days 02:19:04
999997,55466749,2022-09-19 08:21:33,2022-09-19 13:29:47,Noise - Street/Sidewalk,Loud Talking,The Police Department responded to the complai...,Street/Sidewalk,41-22 WARREN STREET,ELMHURST,Precinct 110,21,QUEENS,40.74707979245236,-73.86921337706241,1020489,211485,0 days 05:08:14
999998,55465507,2022-09-19 22:26:38,2022-09-19 23:16:30,Noise - Street/Sidewalk,Loud Talking,The Police Department responded to the complai...,Street/Sidewalk,28 EAST 30 STREET,NEW YORK,Unspecified,02,MANHATTAN,40.74513836661415,-73.98456475397388,988527,210751,0 days 00:49:52
999999,55461722,2022-09-19 15:32:04,2022-09-19 15:59:31,Disorderly Youth,Nuisance/Truant,The Police Department responded to the complai...,Residential Building/House,2932 AVENUE V,BROOKLYN,Precinct 61,46,BROOKLYN,40.598300958849435,-73.94142679784177,1000516,157259,0 days 00:27:27

In [ ]:
NYPD['duration in hours'] = NYPD['duration'].dt.total_seconds() / 3600
NYPD

/var/folders/wy/psj108nd3478hbn8njppcqqc0000gn/T/ipykernel_1444/2644208885.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NYPD['duration in hours'] = NYPD['duration'].dt.total_seconds() / 3600

,unique_key,created_date,closed_date,complaint_type,descriptor,resolution_description,location_type,incident_address,city,police_precinct,council_district,borough,latitude,longitude,x_coordinate_state_plane,y_coordinate_state_plane,duration,duration in hours
0,67231266,2025-12-18 09:07:05,2025-12-18 09:11:16,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,222 BAY 23 STREET,BROOKLYN,Precinct 62,47,BROOKLYN,40.60056381599916,-74.0036803047438,983228,158078,0 days 00:04:11,0.069722
1,67231267,2025-12-18 07:26:24,2025-12-18 21:18:01,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,33 FOUNTAIN AVENUE,BROOKLYN,Precinct 75,37,BROOKLYN,40.6793441596136,-73.87635860175276,1018544,186804,0 days 13:51:37,13.860278
2,67231268,2025-12-18 07:16:56,2025-12-18 10:56:33,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,128-03 25 AVENUE,COLLEGE POINT,Precinct 109,19,QUEENS,40.7765388831131,-73.84065703500205,1028382,222231,0 days 03:39:37,3.660278
3,67231269,2025-12-18 11:51:57,2025-12-18 13:16:52,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,6112 DELAFIELD AVENUE,BRONX,Precinct 50,11,BRONX,40.91038734301122,-73.90215832177458,1011294,270972,0 days 01:24:55,1.415278
4,67231270,2025-12-19 00:29:40,2025-12-19 01:09:00,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,1581 EAST 5 STREET,BROOKLYN,Precinct 66,44,BROOKLYN,40.61230758249285,-73.96960873273228,992688,162358,0 days 00:39:20,0.655556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,55457217,2022-09-18 01:13:43,2022-09-18 02:03:43,Noise - Street/Sidewalk,Loud Music/Party,The Police Department responded to the complai...,Street/Sidewalk,575 OLMSTEAD AVENUE,BRONX,Precinct 43,18,BRONX,40.818193053180714,-73.8510020850777,1025491,237402,0 days 00:50:00,0.833333
999996,55466531,2022-09-19 19:37:52,2022-09-19 21:56:56,Illegal Parking,Double Parked Blocking Vehicle,The Police Department responded to the complai...,Street/Sidewalk,1150 EAST 42 STREET,BROOKLYN,Precinct 63,45,BROOKLYN,40.626818928731794,-73.93546845515829,1002163,167650,0 days 02:19:04,2.317778
999997,55466749,2022-09-19 08:21:33,2022-09-19 13:29:47,Noise - Street/Sidewalk,Loud Talking,The Police Department responded to the complai...,Street/Sidewalk,41-22 WARREN STREET,ELMHURST,Precinct 110,21,QUEENS,40.74707979245236,-73.86921337706241,1020489,211485,0 days 05:08:14,5.137222
999998,55465507,2022-09-19 22:26:38,2022-09-19 23:16:30,Noise - Street/Sidewalk,Loud Talking,The Police Department responded to the complai...,Street/Sidewalk,28 EAST 30 STREET,NEW YORK,Unspecified,02,MANHATTAN,40.74513836661415,-73.98456475397388,988527,210751,0 days 00:49:52,0.831111
999999,55461722,2022-09-19 15:32:04,2022-09-19 15:59:31,Disorderly Youth,Nuisance/Truant,The Police Department responded to the complai...,Residential Building/House,2932 AVENUE V,BROOKLYN,Precinct 61,46,BROOKLYN,40.598300958849435,-73.94142679784177,1000516,157259,0 days 00:27:27,0.457500

## Creating Extra Variables

In [ ]:
# creating a variable where 1 indicates action taken, and 0 indicates no action taken
NYPD.loc[NYPD["resolution_description"] == "The Police Department responded to the complaint and took action to fix the condition.", "took_action"] = 1
NYPD.loc[NYPD["resolution_description"] != "The Police Department responded to the complaint and took action to fix the condition.", "took_action"] = 0

/var/folders/wy/psj108nd3478hbn8njppcqqc0000gn/T/ipykernel_1444/2577981123.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NYPD.loc[NYPD["resolution_description"] == "The Police Department responded to the complaint and with the information available observed no evidence of the violation at that time.", "violation_observed"] = 0
/var/folders/wy/psj108nd3478hbn8njppcqqc0000gn/T/ipykernel_1444/2577981123.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NYPD.loc[NYPD["resolution_description"] == "The Police Department responded to the complaint and took action to fix the condition.", "took_action"] = 1

In [ ]:
NYPD

,unique_key,created_date,closed_date,complaint_type,descriptor,resolution_description,location_type,incident_address,city,police_precinct,council_district,borough,latitude,longitude,x_coordinate_state_plane,y_coordinate_state_plane,duration,duration in hours,violation_observed,took_action
0,67231266,2025-12-18 09:07:05,2025-12-18 09:11:16,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,222 BAY 23 STREET,BROOKLYN,Precinct 62,47,BROOKLYN,40.60056381599916,-74.0036803047438,983228,158078,0 days 00:04:11,0.069722,1.0,0.0
1,67231267,2025-12-18 07:26:24,2025-12-18 21:18:01,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,33 FOUNTAIN AVENUE,BROOKLYN,Precinct 75,37,BROOKLYN,40.6793441596136,-73.87635860175276,1018544,186804,0 days 13:51:37,13.860278,1.0,0.0
2,67231268,2025-12-18 07:16:56,2025-12-18 10:56:33,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,128-03 25 AVENUE,COLLEGE POINT,Precinct 109,19,QUEENS,40.7765388831131,-73.84065703500205,1028382,222231,0 days 03:39:37,3.660278,1.0,0.0
3,67231269,2025-12-18 11:51:57,2025-12-18 13:16:52,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,6112 DELAFIELD AVENUE,BRONX,Precinct 50,11,BRONX,40.91038734301122,-73.90215832177458,1011294,270972,0 days 01:24:55,1.415278,1.0,0.0
4,67231270,2025-12-19 00:29:40,2025-12-19 01:09:00,Blocked Driveway,Partial Access,The New York City Police Department responded ...,Street/Sidewalk,1581 EAST 5 STREET,BROOKLYN,Precinct 66,44,BROOKLYN,40.61230758249285,-73.96960873273228,992688,162358,0 days 00:39:20,0.655556,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,55457217,2022-09-18 01:13:43,2022-09-18 02:03:43,Noise - Street/Sidewalk,Loud Music/Party,The Police Department responded to the complai...,Street/Sidewalk,575 OLMSTEAD AVENUE,BRONX,Precinct 43,18,BRONX,40.818193053180714,-73.8510020850777,1025491,237402,0 days 00:50:00,0.833333,0.0,0.0
999996,55466531,2022-09-19 19:37:52,2022-09-19 21:56:56,Illegal Parking,Double Parked Blocking Vehicle,The Police Department responded to the complai...,Street/Sidewalk,1150 EAST 42 STREET,BROOKLYN,Precinct 63,45,BROOKLYN,40.626818928731794,-73.93546845515829,1002163,167650,0 days 02:19:04,2.317778,1.0,1.0
999997,55466749,2022-09-19 08:21:33,2022-09-19 13:29:47,Noise - Street/Sidewalk,Loud Talking,The Police Department responded to the complai...,Street/Sidewalk,41-22 WARREN STREET,ELMHURST,Precinct 110,21,QUEENS,40.74707979245236,-73.86921337706241,1020489,211485,0 days 05:08:14,5.137222,0.0,0.0
999998,55465507,2022-09-19 22:26:38,2022-09-19 23:16:30,Noise - Street/Sidewalk,Loud Talking,The Police Department responded to the complai...,Street/Sidewalk,28 EAST 30 STREET,NEW YORK,Unspecified,02,MANHATTAN,40.74513836661415,-73.98456475397388,988527,210751,0 days 00:49:52,0.831111,1.0,1.0
999999,55461722,2022-09-19 15:32:04,2022-09-19 15:59:31,Disorderly Youth,Nuisance/Truant,The Police Department responded to the complai...,Residential Building/House,2932 AVENUE V,BROOKLYN,Precinct 61,46,BROOKLYN,40.598300958849435,-73.94142679784177,1000516,157259,0 days 00:27:27,0.457500,1.0,1.0

In [ ]:
NYPD.to_csv('../CSV/NYPD_Complaints_Eric.csv', index=False)